prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: kubernetes-pod-endpoints
        kubernetes_sd_configs:
        - { role: pod }
        relabel_configs:

          # annotation 'prometheus.io/scrape' must be set to true
          - action: keep
            regex: true
            source_labels: [ __meta_kubernetes_pod_annotation_prometheus_io_scrape ]

          # annotation 'prometheus.io/port' should be set
          - action: keep
            regex: true
            source_labels: [ __meta_kubernetes_pod_annotationpresent_prometheus_io_port ]

          # exclude kube-system and monitoring namespaces
          - action: drop
            regex: (kube-system|monitoring)
            source_labels: [ __meta_kubernetes_namespace ]

          - action: replace
            regex: (.+)
            source_labels: [ __meta_kubernetes_pod_annotation_prometheus_io_path ]
            target_label: __metrics_path__

          - action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            source_labels: [ __address__, __meta_kubernetes_pod_annotation_prometheus_io_port ]
            target_label: __address__
